import { styled } from "@mui/system";

interface Styles {
  [key: string]: React.CSSProperties;
}

export const LocatoinParent = styled("div")({
  width: "98%",
  // border: 'solid 2px green',
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  transition: "all linear 0.30s",
  marginLeft: "1%",
  color: "darkslategray",
  backgroundColor: "aliceblue",
  padding: 8,
  borderRadius: 4,
});

export const styles: Styles = {
  location_Parent: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    transition: "all linear 0.30s",
    height: "85vh",
  },
  locatoin_main: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0",
  },
  location_task: {
    width: "25%",
    height: "81vh",
    transition: "all linear 0.30s",
    position: "relative",
    maxHeight: "88vh",
    zIndex: "26",
    ...({
      "@media (maxWidth: 1100px)": { width: "20%", border: "solid 4px red" },
    } as React.CSSProperties),
  },
  location_description: {
    width: "25%",
    height: "85vh",
    transition: "all linear 0.30s",
    position: "relative",
    maxHeight: "88vh",
    zIndex: "25",
    ...({ "@media (maxWidth: 1100px)": { width: "35%" } } as any),
  },
  location_drawing: {
    width: "50%",
    height: "81vh",
    transition: "all linear 0.30s",
    position: "relative",
    marginTop: "15px",
    boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
    borderRadius: "4px",
    zIndex: "24",
    ...({ "@media (maxWidth: 1100px)": { width: "45%" } } as any),
  },
  location_task_min: {
    width: "7%",
    height: "85vh",
    transition: "all linear 0.30s",
    position: "relative",
    maxHeight: "88vh",
    zIndex: "26",
  },
  location_drawing_max: {
    width: "68%",
    height: "81vh",
    transition: "all linear 0.30s",
    position: "relative",
    overflowY: "scroll",
    overflowX: "hidden",
    marginTop: "15px",
    boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
    borderRadius: "4px",
    backgroundColor: "#FFF",
    zIndex: "24",
  },
  location_description_max: {
    width: "43%",
    height: "85vh",
    transition: "all linear 0.30s",
    position: "relative",
    transform: "translate(18px,0px)",
    zIndex: "25",
  },
  location_btn: {
    height: "max-content",
    width: "max-contnet",
    transition: "all linear 0.15s",
    position: "absolute",
    top: "50%",
    left: "95%",
    transform: "rotate(0deg)",
    zIndex: "125",
    border: "solid 1px black",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    paddingLeft: "5px",
    paddingRight: "5px",
    paddingTop: "10px",
    paddingBottom: "10px",
  },
  location_btn_left: {
    height: "max-content",
    width: "max-contnet",
    transition: "all linear 0.15s",
    position: "absolute",
    top: "52.5%",
    left: "95%",
    transform: "rotate(0deg)",
    border: "solid 1px black",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    paddingLeft: "5px",
    paddingRight: "5px",
    paddingTop: "10px",
    paddingBottom: "10px",
  },
  location_btn_change: {
    height: "max-content",
    width: "max-contnet",
    transition: "all linear 0.15s",
    position: "absolute",
    top: "50%",
    left: "95%",
    transform: "rotate(180deg)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    paddingLeft: "5px",
    paddingRight: "5px",
    paddingTop: "10px",
    paddingBottom: "10px",
  },
  location_all_taks: {
    width: "95%",
    height: "81vh",
    overflowY: "scroll",
    overflowX: "hidden",
    marginTop: "15px",
    boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
    borderRadius: "4px",
    backgroundColor: "#FFF",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  locatoin_task_header: {
    height: "max-content",
    width: "100%",
  },
  location_task_bottom: {
    height: "80%",
    width: "100%",
  },
  location_all_drawings: {
    width: "95%",
    height: "85vh",
    overflowY: "scroll",
    overflowX: "hidden",
  },
};
