import ClearIconSvgGray from "../icons/CustomSvgIcon/ClearIconSvgGray";
import ForwardIcon from "./TaskIcons/ForwardIcon";
import ReplyIcon from "./TaskIcons/ReplyIcon";
export * from "./ConfigIcons";
export { AttachmentIcon } from "./attachment/Attachment";
export { ViewCommentsIco } from "./attachment/ViewCommentsIco";
export { ChatIcon } from "./chat/Chat";
export { DeleteIcon } from "./delete/Delete";
export { EditIcon } from "./edit/Edit";
export { EyeIcon } from "./eye/Eye";
export { GroupAdminIcon } from "./groupAdmin/GroupAdmin";
export { InfoIcon } from "./info/Info";
export { ListViewIcon } from "./list-view/ListView";
export { MediaIcon } from "./media/Media";
export { MemberIcon } from "./member/Member";
export { MesageIcon } from "./mesage/Mesage";
export { NotificationIcon } from "./notification/Notification";
export { ProfileIcon } from "./profile/Profile";
export { QuestionnairIcon } from "./questionnair/Questionnair";
export { RemoveIcon } from "./remove/Remove";
export { SendIcon } from "./send/Send";
export { ClearIconSvgGray, ForwardIcon, ReplyIcon };
