export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'
export const SET_NAVBAR_OPEN = 'SET_NAVBAR_OPEN'
export const SET_COLLAPSE = 'SET_COLLAPSE'
export const SET_SIDEBAR_CONFIG = 'SET_SIDEBAR_CONFIG';
export const CEIBRO_LIVE_EVENT_BY_SERVER = 'CEIBRO_LIVE_EVENT_BY_SERVER'
export const CEIBRO_LIVE_EVENT_BY_USER = 'CEIBRO_LIVE_EVENT_BY_USER'