
export const AUTH_CONFIG = {
    RESEND_OTP: "RESEND_OTP"
}

export const REGISTER = "REGISTER";
export const REGISTER_CONFIRMATION = "REGISTER_CONFIRMATION";
export const REGISTER_PROFILE_SETUP = "REGISTER_PROFILE_SETUP";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const GET_USERS = "GET_USERS";
export const CREATE_ROOM = "CREATE_ROOM";
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_MY_PROFILE = "UPDATE_MY_PROFILE";
export const OTP_VERIFY = "OTP_VERIFY";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SEND_VERIFY_EMAIL = "SEND_VERIFY_EMAIL";
