export const GET_CHAT = 'GET_CHAT';
export const GET_CHAT_API = 'GET_CHAT_API';
export const PUSH_MESSAGE = 'PUSH_MESSAGE';
export const SET_SELECTED_CHAT = 'SET_SELECTED_CHAT';
export const CLEAR_SELECTED_CHAT = 'CLEAR_SELECTED_CHAT';
export const GET_MESSAGES = 'GET_MESSAGES';
export const PUSH_TO_UNSELECTED = 'PUSH_TO_UNSELECTED';
export const SET_MESSAGE_READ = 'SET_MESSAGE_READ';
export const SET_CHAT_TYPE = 'SET_CHAT_TYPE';
export const SET_CHAT_SEARCH = 'SET_CHAT_SEARCH';
export const MUTE_CHAT = 'MUTE_CHAT';
export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const SET_CHAT_SIDE_BAR = 'SET_CHAT_SIDE_BAR';
export const SET_REPLY_TO_ID = 'SET_REPLY_TO_ID';
export const SEND_REPLY_MESSAGE = "SEND_REPLY_MESSAGE";




//  SOCKET EVENTS

export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";