export const GET_CHAT = "GET_CHAT";
export const GET_CHAT_API = "GET_CHAT_API";
export const PUSH_MESSAGE = "PUSH_MESSAGE";
export const SAVE_MESSAGES = "SAVE_MESSAGES";
export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";
export const CLEAR_SELECTED_CHAT = "CLEAR_SELECTED_CHAT";
export const GET_MESSAGES = "GET_MESSAGES";
export const PUSH_TO_UNSELECTED = "PUSH_TO_UNSELECTED";
export const SET_MESSAGE_READ = "SET_MESSAGE_READ";
export const SET_CHAT_TYPE = "SET_CHAT_TYPE";
export const SET_CHAT_SEARCH = "SET_CHAT_SEARCH";
export const MUTE_CHAT = "MUTE_CHAT";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const SET_CHAT_SIDE_BAR = "SET_CHAT_SIDE_BAR";
export const SET_REPLY_TO_ID = "SET_REPLY_TO_ID";
export const SEND_REPLY_MESSAGE = "SEND_REPLY_MESSAGE";
export const PIN_MESSAGE = "PIN_MESSAGE";
export const SET_FAVOURITE_FILTER = "SET_FAVOURITE_FILTER";
export const GET_UNREAD_CHAT_COUNT = "GET_UNREAD_CHAT_COUNT";
export const OPEN_QUESTIONIAR_DRAWER = "OPEN_QUESTIONIAR_DRAWER";
export const CLOSE_QUESTIONIAR_DRAWER = "CLOSE_QUESTIONIAR_DRAWER";
export const SET_QUESTIONS = "SET_QUESTIONS";
export const GET_ROOM_MEDIA = "GET_ROOM_MEDIA";
export const SET_MEMBERS_DIALOG = "SET_MEMBERS_DIALOG";
export const SET_TEMP_MEMBERS_DIALOG = "SET_TEMP_MEMBERS_DIALOG";
export const ADD_MEMBERS_TO_CHAT = "ADD_MEMBERS_TO_CHAT";
export const ADD_TEMP_MEMBERS_TO_CHAT = "ADD_TEMP_MEMBERS_TO_CHAT";


// users constants
export const GET_ALL_USERS = "GET_ALL_USERS"; 
//  SOCKET EVENTS

export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
