
export const DOCS_CONFIG = {
    
    // API'S ACTION
    UPLOAD_DOCS_BY_MODULNAME_AND_ID: 'UPLOAD_DOCS_BY_MODULNAME_AND_ID',
    GET_DOCS_BY_MODULNAME_AND_ID: 'GET_DOCS_BY_MODULNAME_AND_ID',

    // SOCKET EVENT ACTION
    FILE_UPLOAD_PROGRESS: 'FILE_UPLOAD_PROGRESS',
    PUSH_FILE_UPLAOD_RESPONSE: 'PUSH_FILE_UPLAOD_RESPONSE',
    UPDATE_FILE_UPLAOD_RESPONSE: 'UPDATE_FILE_UPLAOD_RESPONSE',
    FILE_UPLOADED: 'FILE_UPLOADED',
    FILES_UPLOAD_COMPLETED: 'FILES_UPLOAD_COMPLETED',
    
    // STORE ACTION
    CLEAR_FILE_BEING_UPLOADED: 'CLEAR_FILE_BEING_UPLOADED',

    SET_SELECTED_FILES_TO_BE_UPLOADED:'SET_SELECTED_FILES_TO_BE_UPLOADED',
    UPLAOD_FILES_NOW:'UPLAOD_FILES_NOW',
    CLEAR_SELECTED_FILES_TO_BE_UPLOADED: 'CLEAR_SELECTED_FILES_TO_BE_UPLOADED',

    SET_SELECTED_MODULE_ID: 'SET_SELECTED_MODULE_ID',
}
