
export const TASK_CONFIG = {
  // task
  GET_TASK: 'GET_TASK',
  PUSH_TASK_TO_STORE: 'PUSH_TASK_TO_STORE',
  UPDATE_TASK_IN_STORE: 'UPDATE_TASK_IN_STORE',
  CREATE_TASK: 'CREATE_TASK',
  TASK_ASSIGNED_TO_MEMBERS: 'TASK_ASSIGNED_TO_MEMBERS',
  EDIT_TASK: 'EDIT_TASK',
  DELETE_TASK: 'DELETE_TASK',
  SELECTED_TASK_ID: 'SELECTED_TASK_ID',
  SET_SELECTED_TASK: 'SET_SELECTED_TASK',

  // subtask
  GET_ALL_SUBTASK_LIST: 'GET_ALL_SUBTASK_LIST',
  GET_ALL_SUBTASK_OF_TASK: 'GET_ALL_SUBTASK_OF_TASK',
  CREATE_SUB_TASK: 'CREATE_SUB_TASK',
  PUSH_SUB_TASK_TO_STORE: 'PUSH_SUB_TASK_TO_STORE',

  // drawer & modal 
  OPEN_NEW_TASK: 'OPEN_NEW_TASK',
  CLOSE_NEW_TASK: 'CLOSE_NEW_TASK',
  OPEN_TASK_MODAL: 'OPEN_TASK_MODAL',
  OPEN_TASK_DRAWER: 'OPEN_TASK_DRAWER',
  CLOSE_TASK_DRAWER: 'CLOSE_TASK_DRAWER',

  // other
  SET_MENUE: 'SET_MENUE',
  PROJECT_MEMBERS_OF_SELECTED_TASK: 'PROJECT_MEMBERS_OF_SELECTED_TASK',
  SELECTED_TASK_ADMINS: 'SELECTED_TASK_ADMINS',

  // task socket events
  TASK_CREATED: 'TASK_CREATED',
  SUB_TASK_CREATED: 'SUB_TASK_CREATED',
  TASK_UPDATE_PUBLIC: 'TASK_UPDATE_PUBLIC',
  TASK_UPDATE_PRIVATE: 'TASK_UPDATE_PRIVATE',
  SUB_TASK_UPDATE_PUBLIC: 'SUB_TASK_UPDATE_PUBLIC',
  SUB_TASK_UPDATE_PRIVATE: 'SUB_TASK_UPDATE_PRIVATE',
  TASK_SUBTASK_UPDATED: 'TASK_SUBTASK_UPDATED',
}