export const TASK_CONFIG = {
  // task
  SYNC_ALL_TASKS: "SYNC_ALL_TASKS",
  CREATE_TASK: "CREATE_TASK",
  CREATE_TOPIC: "CREATE_TOPIC",
  GET_ALL_TOPIC: "GET_ALL_TOPIC",
  DELETE_TOPIC: "DELETE_TOPIC",
  FORWARD_TASK: "FORWARD_TASK",
  TASK_SEEN: "TASK_SEEN",
  TASK_SHOW: "TASK_SHOW",
  TASK_HIDE: "TASK_HIDE",
  TASK_CANCELED: "TASK_CANCELED",
  TASK_UN_CANCEL: "TASK_UN_CANCEL",
  TASK_EVENT_WITH_FILES: "TASK_EVENT_WITH_FILES",

  GET_ALL_TASK_TO_ME: "GET_ALL_TASK_TO_ME",
  GET_ALL_TASK_FROM_ME: "GET_ALL_TASK_FROM_ME",
  GET_ALL_TASK_HIDDEN: "GET_ALL_TASK_HIDDEN",
  PUSH_NEW_TASK_TO_STORE: "PUSH_NEW_TASK_TO_STORE",
  PUSH_TOPIC_IN_STORE: "PUSH_TOPIC_IN_STORE",
  PULL_TASK_FROM_STORE: "PULL_TASK_FROM_STORE",
  UPDATE_TASK_IN_STORE: "UPDATE_TASK_IN_STORE",
  UPDATE_TASK_WITH_EVENTS: "UPDATE_TASK_WITH_EVENTS",
  UPLOAD_TASK_DOCS: "UPLOAD_TASK_DOCS",

  SELECTED_TASK_FILTER: "SELECTED_TASK_FILTER",

  // socket events
  TASK_CREATED: "TASK_CREATED",
  TASK_FORWARDED: "TASK_FORWARDED",
  NEW_TASK_COMMENT: "NEW_TASK_COMMENT",
  TOPIC_CREATED: "TOPIC_CREATED",
  TASK_DONE: "TASK_DONE",
  CANCELED_TASK: "CANCELED_TASK",
  TASK_HIDDEN: "TASK_HIDDEN",
  TASK_SHOWN: "TASK_SHOWN",
  UN_CANCEL_TASK: "UN_CANCEL_TASK",
  TASK_UPDATED_WITH_FIELS: "TASK_UPDATED_WITH_FIELS",
  SELECTED_TASK_ADMINS: "SELECTED_TASK_ADMINS"
};
