export const SEND_INVITATION = "SEND_INVITATION";
export const GET_MY_ALL_INVITES = "GET_MY_ALL_INVITES";
export const ACCEPT_INVITE = "ACCEPT_INVITE";
export const GET_MY_CONNECTIONS = "GET_MY_CONNECTIONS";
export const ACCEPT_ALL_INVITES = "ACCEPT_ALL_INVITES";
export const GET_MY_INVITES_COUNT = "GET_MY_INVITES_COUNT";

