name: CICD for Ceibro Frontend
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: yarn install build
        run: |
          yarn install
          yarn build
        
        env:
          CI: true
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: "dev.ceibro.ee"
          username: ${{ secrets.USER}}
          key: ${{ secrets.KEY}}
          port: ${{ secrets.PORT}}

          script: |
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.33.8/install.sh | bash
              . ~/.nvm/nvm.sh
              nvm install 14
              npm install -g pm2

              cd ~/CEIBRODEPLOY/public/
              git pull origin dev
              pm2 reload 0